# Generated by Django 4.1.4 on 2024-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=200)),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
                ('customer_name', models.CharField(max_length=200)),
                ('gp', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('user_contact_name', models.CharField(max_length=200)),
                ('dealer_name', models.CharField(max_length=200)),
                ('bill_no', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('bill_to', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('model_or_frame', models.CharField(max_length=200)),
                ('sr_no_or_mc_no', models.CharField(max_length=200)),
                ('rotor_voltage', models.CharField(max_length=200)),
                ('rotor_current', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('kw', models.CharField(max_length=200)),
                ('rpm', models.CharField(max_length=200)),
                ('stator_current', models.CharField(max_length=200)),
                ('stator_voltage', models.CharField(max_length=200)),
                ('defect', models.TextField()),
                ('cutting', models.TextField()),
                ('rewinding', models.TextField()),
                ('fitting', models.TextField()),
                ('housing_machining', models.TextField()),
                ('shaft_machining', models.TextField()),
                ('bearing', models.TextField()),
                ('terminal', models.TextField()),
                ('cooling_fan', models.TextField()),
                ('welding', models.TextField()),
                ('balancing', models.TextField()),
                ('lath_work', models.TextField()),
                ('other_1', models.TextField()),
                ('other_2', models.TextField()),
                ('our_bill_or_challan_no', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Job Register',
            },
        ),
    ]
