# Generated by Django 4.1.4 on 2024-03-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0002_alter_jobregister_options_testreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=500)),
                ('make', models.CharField(max_length=500)),
                ('kw', models.CharField(max_length=500)),
                ('pole_rpm', models.CharField(max_length=500)),
                ('ph', models.CharField(max_length=500)),
                ('no_of_slots', models.CharField(max_length=500)),
                ('running_wire_gauge', models.CharField(max_length=500)),
                ('running_pitch', models.CharField(max_length=500)),
                ('running_turn', models.CharField(max_length=500)),
                ('starting_wire_gauge', models.CharField(max_length=500)),
                ('starting_pitch', models.CharField(max_length=500)),
                ('starting_turn', models.CharField(max_length=500)),
                ('coil_weight', models.CharField(max_length=500)),
                ('total_weight', models.CharField(max_length=500)),
                ('core_length', models.CharField(max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader_app.jobregister')),
            ],
            options={
                'verbose_name_plural': 'Test Reports',
            },
        ),
    ]
