# Generated by Django 4.1.4 on 2024-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0004_photo_scope_of_work_jobregister_inspection_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope_of_work',
            name='terms_condition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scope_of_work',
            name='testing_and_inspection',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
