# Generated by Django 4.1.4 on 2024-03-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0005_scope_of_work_terms_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quotation_no', models.CharField(max_length=200)),
                ('quotation_file', models.FileField(upload_to='quotations/')),
                ('comments', models.TextField(blank=True, help_text='comments if any', null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader_app.jobregister')),
            ],
            options={
                'verbose_name_plural': 'Quotations',
            },
        ),
    ]
