# Generated by Django 4.1.4 on 2024-03-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0007_inspectionreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_details', models.TextField()),
                ('jobs_tests_carried_out', models.TextField()),
                ('customer_details', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader_app.jobregister')),
            ],
            options={
                'verbose_name_plural': 'Test Report Documents',
            },
        ),
    ]
